export const ROLE_PERMISSIONS: Record<string, string[]> = {
  owner: ['*'],
  manager: [
    'products:read',
    'products:create',
    'products:update',
    'products:delete',
    'inventory:read',
    'inventory:adjust',
    'suppliers:read',
    'suppliers:create',
    'suppliers:update',
    'suppliers:delete',
    'purchases:read',
    'purchases:create',
    'purchases:approve',
    'customers:read',
    'customers:create',
    'customers:update',
    'customers:delete',
    'sales:create',
    'sales:read',
    'sales:refund',
    'payments:create',
    'payments:update',
    'payments:delete',
    'expenses:read',
    'expenses:create',
    'expenses:update',
    'expenses:delete',
    'reports:view',
    'dashboard:read',
    'settings:read',
    'settings:update',
  ],
  cashier: [
    'products:read',
    'inventory:read',
    'customers:read',
    'customers:create',
    'customers:update',
    'customers:delete',
    'sales:create',
    'sales:read',
    'payments:create',
    'payments:update',
    'payments:delete',
  ],
  inventory_staff: [
    'products:read',
    'products:create',
    'products:update',
    'products:delete',
    'inventory:read',
    'inventory:adjust',
    'suppliers:read',
    'suppliers:create',
    'suppliers:update',
    'suppliers:delete',
    'purchases:read',
    'purchases:create',
  ],
  delivery_staff: [
    'sales:read',
    'customers:read',
  ],
};
