import React, { useState, useEffect } from 'react';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import Select from '@mui/material/Select';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import FormInput from '@/components/common/FormInput';
import PrimaryButton from '@/components/common/PrimaryButton';
import SecondaryButton from '@/components/common/SecondaryButton';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import CheckIcon from '@mui/icons-material/Check';

import { useDispatch } from 'react-redux';
import { addNotification } from '@/store/notificationsSlice';

import {
  useCreateStaffMutation,
  useUpdateStaffMutation,
  useGetRolesListQuery,
  StaffUser,
} from '../usersApi';

interface StaffFormDialogProps {
  open: boolean;
  staff: StaffUser | null;
  onClose: () => void;
}

export const StaffFormDialog: React.FC<StaffFormDialogProps> = ({ open, staff, onClose }) => {
  const dispatch = useDispatch();
  const isEdit = Boolean(staff);

  // Form Fields State
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [roleId, setRoleId] = useState('');
  const [employeeId, setEmployeeId] = useState('');
  const [joiningDate, setJoiningDate] = useState('');
  const [department, setDepartment] = useState('');

  // Password Recovery / Copy State
  const [tempPassword, setTempPassword] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Mutations & Roles List
  const { data: rolesResponse } = useGetRolesListQuery();
  const [createStaff, { isLoading: isCreating }] = useCreateStaffMutation();
  const [updateStaff, { isLoading: isUpdating }] = useUpdateStaffMutation();

  const roles = rolesResponse?.data || [];

  // Populate form if editing
  useEffect(() => {
    if (staff) {
      setFullName(staff.fullName || '');
      setEmail(staff.email || '');
      setPhone(staff.phone || '');
      setRoleId(staff.role?.id || '');
      setEmployeeId(staff.employeeId || '');
      setDepartment(staff.department || '');
      if (staff.joiningDate) {
        setJoiningDate(new Date(staff.joiningDate).toISOString().substring(0, 10));
      } else {
        setJoiningDate('');
      }
    } else {
      setFullName('');
      setEmail('');
      setPhone('');
      setRoleId('');
      setEmployeeId('');
      setJoiningDate('');
      setDepartment('');
    }
    setTempPassword(null);
    setCopied(false);
  }, [staff, open]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const payload = {
      fullName,
      phone: phone || undefined,
      employeeId: employeeId || undefined,
      joiningDate: joiningDate || undefined,
      department: department || undefined,
    };

    try {
      if (isEdit && staff) {
        await updateStaff({ id: staff.id, body: payload }).unwrap();
        dispatch(
          addNotification({
            title: 'Staff Details Updated',
            message: `Profile details for ${fullName} have been updated.`,
            type: 'info',
          })
        );
        onClose();
      } else {
        const response = await createStaff({
          ...payload,
          email,
          roleId,
        }).unwrap();

        const roleName = roles.find((r) => (r.id || r._id) === roleId)?.name || 'Staff';
        dispatch(
          addNotification({
            title: 'New Staff Registered',
            message: `Staff member ${fullName} was registered successfully as ${roleName}.`,
            type: 'success',
          })
        );

        // Capture temporary password generated by the backend
        if (response?.data?.temporaryPassword) {
          setTempPassword(response.data.temporaryPassword);
        } else {
          onClose();
        }
      }
    } catch (err) {
      console.error('Failed to save staff member:', err);
    }
  };

  const handleCopy = () => {
    if (tempPassword) {
      navigator.clipboard.writeText(tempPassword);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const isLoading = isCreating || isUpdating;

  return (
    <Dialog
      open={open}
      onClose={isLoading ? undefined : onClose}
      maxWidth="sm"
      fullWidth
      slotProps={{
        paper: {
          className: '!rounded-2xl !p-2 border border-slate-100 shadow-2xl max-w-[500px]',
        },
      }}
    >
      <DialogTitle className="!font-heading !font-black !text-base !text-secondary !pb-2 select-none">
        {tempPassword ? 'Account Registered Successfully!' : isEdit ? 'Modify Staff Member' : 'Register Staff Member'}
      </DialogTitle>

      {tempPassword ? (
        // Success password copy view
        <div className="p-6 text-center select-none">
          <div className="h-12 w-12 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4 border border-emerald-100">
            <CheckIcon className="h-6 w-6" />
          </div>
          <p className="text-sm font-semibold text-slate-700 font-sans leading-relaxed">
            Staff account for <span className="font-extrabold text-secondary">{fullName}</span> has been created.
          </p>
          <p className="text-xs text-slate-400 font-sans mt-1">
            Please copy this temporary password and securely send it to them. They can use it to log in and change their password.
          </p>

          <div className="mt-6 flex items-center justify-between bg-slate-50 border border-slate-200/80 p-3.5 rounded-xl gap-3">
            <span className="text-sm font-mono font-bold tracking-wider text-slate-800 select-all">
              {tempPassword}
            </span>
            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-semibold font-sans transition-all duration-200 ${
                copied
                  ? 'bg-emerald-50 border-emerald-200 text-emerald-600'
                  : 'bg-white hover:bg-slate-50 border-slate-200 text-slate-600 hover:text-slate-800'
              }`}
            >
              {copied ? (
                <>
                  <CheckIcon className="h-3.5 w-3.5" />
                  Copied!
                </>
              ) : (
                <>
                  <ContentCopyIcon className="h-3.5 w-3.5" />
                  Copy
                </>
              )}
            </button>
          </div>

          <div className="mt-6">
            <PrimaryButton onClick={onClose} className="!w-full !py-2.5">
              Done & Close
            </PrimaryButton>
          </div>
        </div>
      ) : (
        // Standard user input form view
        <form onSubmit={handleSubmit}>
          <DialogContent className="!pb-6 !pt-2 space-y-4 max-h-[70vh] overflow-y-auto scrollbar-thin">
            <FormInput
              label="Full Name"
              value={fullName}
              onChange={(e) => setFullName(e.target.value)}
              placeholder="e.g. Rahul Sharma"
              required
              disabled={isLoading}
            />

            <FormInput
              label="Email Address"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="e.g. rahul@aashiyana.com"
              required
              disabled={isEdit || isLoading} // email is immutable for staff after creation
            />

            <FormInput
              label="Phone Number"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              placeholder="e.g. 9876543210"
              disabled={isLoading}
            />

            {!isEdit && (
              <FormControl fullWidth className="space-y-1.5">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider select-none">
                  Assigned Role <span className="text-red-500">*</span>
                </label>
                <Select
                  value={roleId}
                  onChange={(e) => setRoleId(e.target.value)}
                  displayEmpty
                  required
                  disabled={isLoading}
                  className="!font-sans !text-sm !bg-slate-50 !rounded-xl !border-slate-200"
                  classes={{ select: '!py-2.5 !px-3.5' }}
                >
                  <MenuItem value="" disabled className="!text-sm !font-sans text-slate-400">
                    Select Role...
                  </MenuItem>
                  {roles.map((r) => (
                    <MenuItem key={r.id || r._id} value={r.id || r._id} className="!text-sm !font-sans">
                      {r.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <FormInput
                label="Employee ID"
                value={employeeId}
                onChange={(e) => setEmployeeId(e.target.value)}
                placeholder="e.g. EMP-001"
                disabled={isLoading}
              />

              <FormInput
                label="Department"
                value={department}
                onChange={(e) => setDepartment(e.target.value)}
                placeholder="e.g. Sales"
                disabled={isLoading}
              />
            </div>

            <FormInput
              label="Joining Date"
              type="date"
              value={joiningDate}
              onChange={(e) => setJoiningDate(e.target.value)}
              disabled={isLoading}
            />
          </DialogContent>

          <DialogActions className="!px-6 !pb-4 !gap-3 select-none">
            <SecondaryButton type="button" onClick={onClose} disabled={isLoading} className="!py-2.5 !px-4">
              Cancel
            </SecondaryButton>
            <PrimaryButton type="submit" loading={isLoading} className="!py-2.5 !px-4">
              {isEdit ? 'Save Changes' : 'Register Staff'}
            </PrimaryButton>
          </DialogActions>
        </form>
      )}
    </Dialog>
  );
};

export default StaffFormDialog;
